version: '3.8'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: Sharad
      MONGO_INITDB_ROOT_PASSWORD: 12345
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      #- MONGO_URI=mongodb://mernuser:mernpass@mongo:27017/loginApp?authSource=admin
       - MONGO_URI=mongodb+srv://Sharad:12345@cluster0.nmowc.mongodb.net/loginApp?retryWrites=true&w=majority
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend

volumes:
  mongo-data:
